name: Deploy Docker Container to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Configurar la clave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Desplegar a la instancia EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_INSTANCE_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull jadem1203/hola-mundo-web:latest
            docker run -d --name html-container -p 80:80 jadem1203/hola-mundo-web:latest
