name: CI/CD for Docker Image Deployment

on:
  # Detecta cambios en archivos HTML para construir y subir la imagen
  push:
    branches:
      - main
    paths:
      - "**/*.html"

jobs:
  # Trabajo 1: Actualizar la imagen Docker
  update_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out repository
        uses: actions/checkout@v4

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir y subir la imagen actualizada
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .               # Usa el Dockerfile desde la raíz
          push: true               # Sube la imagen a Docker Hub
          tags: jadem1203/hola-mundo-web:latest # Etiqueta como "latest"

  # Trabajo 2: Desplegar la nueva imagen en la instancia EC2
  deploy:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest

    needs: update_docker_image # Espera que se complete el trabajo de actualizar la imagen
    steps:
      # Paso 1: Configurar la clave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 2: Conectarse a la instancia EC2 y actualizar el contenedor
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_INSTANCE_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull jadem1203/hola-mundo-web:latest
            docker run -d --name html-container -p 80:80 jadem1203/hola-mundo-web:latest
